version: 2.1
jobs:
  unit-tests:
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - run:
          name: "Install app dependencies"
          command: yarn
      - run:
          name: "Run app unit tests"
          command: yarn redwood test
  sast:
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - run:
          name: "Install app dependencies"
          command: yarn
      - run:
          name: "Execute retire.js"
          command: cd web; retire --path web

workflows:
  deploy-to-env:
    jobs:
      - unit-tests
      - sast