version: 2.1
jobs:
  unit-test:
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: yarn
      - run:
          name: "run front-end tests"
          command: yarn redwood test
  build-app:
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: yarn
      - run:
          name: "build app"
          command: yarn redwood build

workflows:
  deploy-workflow:
    jobs:
      - unit-test
      - build-app
