version: 2.1 
jobs: 
  unit-tests: 
    docker: 
      - image: cimg/node:14.20.0
    steps: 
      - checkout 
      - run: 
          name: "install dependencies" 
          command: yarn upgrade 
      - run: 
          name: "run project unit tests" 
          command: yarn redwood test 
 
workflows: 
  Testing...: 
    jobs: 
      - unit-tests
