version: 2.1
jobs:
  unit-test:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run:
          name: "run front-end tests"
          command: cd web; mkdir ~/.npm-global; npm config set prefix '~/.npm-global'; export PATH=~/.npm-global/bin:$PATH; source ~/.profile; npm test
  static-test:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run:
          name: "install web"
          command: cd web; mkdir ~/.npm-global; npm config set prefix '~/.npm-global'; export PATH=~/.npm-global/bin:$PATH; source ~/.profile; npm install
      - run:
          name: "install retire"
          command: cd web; npm config list; npm config set prefix '~/.npm-global'; export PATH=~/.npm-global/bin:$PATH; source ~/.profile; npm install -g retire
      - run:
          name: "SAST testing"
          command: export PATH=~/.npm-global/bin:$PATH; retire --path web
  husky-ci:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run:
          name: "Build app"
          environment:
            HUSKYCI_CLIENT_URL: http://urlto.huskyci-client
            HUSKYCI_CLIENT_API_ADDR: http://urlto.huskyci-API
            HUSKYCI_CLIENT_REPO_URL: git@github.com:flippedcoder/dev-sec-ops-training.git
            HUSKYCI_CLIENT_REPO_BRANCH: main
            HUSKYCI_CLIENT_API_USE_HTTPS: "false"
          command: wget $HUSKYCI_CLIENT_URL/huskyci-client & chmod +x huskyci-client & ./huskyci-client
  build-app:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Build app"
          command: "echo App built"
  deploy-qa:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run:
          name: "deploy to QA env"
          command: echo "Deployed to QA environment"
  nuclei:
    docker:
      - image: cimg/go
    steps:
      - checkout
      - run:
          name: "install nuclei-cli"
          command: go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          # command: git clone https://github.com/projectdiscovery/nuclei.git; cd nuclei/v2/cmd/nuclei; go build; mv nuclei /usr/local/bin/; nuclei -version
      - run:
          name: "Nuclei scan on staging"
          command: nuclei -u https://www.flippedcoding.com
  interactive-test:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run:
          name: "install nexploit-cli"
          command: cd web; npm config list; npm config set prefix '~/.npm-global'; export PATH=~/.npm-global/bin:$PATH; source ~/.profile; npm install -g @neuralegion/nexploit-cli
      - run:
          name: "IAST testing"
          command: nexploit-cli scan:run --token $NEXPLOIT_TOKEN --name "scan from CircleCI" >> $BASH_ENV
      - run:
          name: Scan output
          command: printf "Scan available at https://nexploit.app/scans/{$NEXPLOIT_ID}”


workflows:
  deploy-to-qa-workflow:
    jobs:
      - static-test
      - unit-test
      - husky-ci
      - build-app
      - deploy-qa
      - nuclei
      - interactive-test
