version: 2.1
jobs:
  unit-tests:
    docker:
      - image: cimg/node:20.12.2
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: yarn
      - run:
          name: "run project unit tests"
          command: yarn rw test


workflows: 
  deploy-to-qa: 
    jobs: 
      - unit-tests
     
